<?php
require 'config.php'; require 'includes/functions.php';
$pageTitle='Marketplace'; $activePage='marketplace';
$search=trim($_GET['search']??''); $type=trim($_GET['type']??''); $region_id=(int)($_GET['region_id']??0); $crop_id=(int)($_GET['crop_id']??0);
$sql="SELECT l.id,l.quantity,l.price,l.note,l.featured,l.views,l.created_at,u.name,u.phone,c.name AS crop_name,un.name AS unit_name,r.name AS region_name,lt.name AS listing_type FROM listings l JOIN users u ON u.id=l.user_id JOIN crops c ON c.id=l.crop_id JOIN units un ON un.id=l.unit_id JOIN regions r ON r.id=l.region_id JOIN listing_types lt ON lt.id=l.listing_type_id JOIN listing_statuses ls ON ls.id=l.status_id WHERE ls.name='active'";
$params=[];
if($search!==''){ $sql.=" AND (c.name LIKE ? OR r.name LIKE ? OR u.name LIKE ? OR l.note LIKE ?)"; $s="%$search%"; array_push($params,$s,$s,$s,$s); }
if($type!==''){ $sql.=' AND lt.name=?'; $params[]=$type; }
if($region_id>0){ $sql.=' AND l.region_id=?'; $params[]=$region_id; }
if($crop_id>0){ $sql.=' AND l.crop_id=?'; $params[]=$crop_id; }
$sql.=' ORDER BY l.featured DESC,l.created_at DESC'; $stmt=$pdo->prepare($sql); $stmt->execute($params); $listings=$stmt->fetchAll();
$regions=$pdo->query('SELECT id,name FROM regions ORDER BY name')->fetchAll(); $crops=$pdo->query('SELECT id,name FROM crops ORDER BY name')->fetchAll(); $types=$pdo->query('SELECT id,name FROM listing_types ORDER BY id')->fetchAll();
require 'includes/header.php'; ?>
<section class="block top-space"><div class="section-head"><div><p class="eyebrow">LIVE MARKET</p><h1>Marketplace</h1><p class="sub-small">Browse people buying and selling agricultural products across Tanzania.</p></div><a class="btn" href="<?= current_user()?'post.php':'login.php' ?>"><?= current_user()?'Post a listing':'Login to post' ?></a></div>
<form class="filters" method="get"><input type="search" name="search" placeholder="Search crop, region, seller..." value="<?= e($search) ?>"><select name="type"><option value="">All types</option><?php foreach($types as $t): ?><option value="<?= e($t['name']) ?>" <?= $type===$t['name']?'selected':'' ?>><?= e(ucfirst($t['name'])) ?></option><?php endforeach; ?></select><select name="region_id"><option value="0">All regions</option><?php foreach($regions as $r): ?><option value="<?= (int)$r['id'] ?>" <?= $region_id===(int)$r['id']?'selected':'' ?>><?= e($r['name']) ?></option><?php endforeach; ?></select><select name="crop_id"><option value="0">All crops</option><?php foreach($crops as $c): ?><option value="<?= (int)$c['id'] ?>" <?= $crop_id===(int)$c['id']?'selected':'' ?>><?= e($c['name']) ?></option><?php endforeach; ?></select><button class="btn" type="submit">Search</button><a class="btn btn-ghost" href="marketplace.php">Clear</a></form></section>
<section class="block"><div class="section-head"><h2><?= number_format(count($listings)) ?> listings</h2></div><div class="grid"><?php if(!$listings): ?><div class="empty">No listings found. Try changing your filters.</div><?php else: foreach($listings as $l): ?><div class="card"><div class="card-top"><div class="crop-name"><?= e($l['crop_name']) ?></div><div class="tag <?= e($l['listing_type']) ?>"><?= $l['listing_type']==='sell'?'Selling':'Buying' ?></div></div><div class="price-row"><?= e(format_money($l['price'])) ?> <span>/ <?= e($l['unit_name']) ?></span></div><div class="meta"><b><?= e((string)$l['quantity']) ?></b> <?= e($l['unit_name']) ?></div><div class="meta"><?= e($l['region_name']) ?></div><?php if($l['note']): ?><div class="meta note"><?= e($l['note']) ?></div><?php endif; ?><div class="card-footer"><span class="seller"><?= e($l['name']) ?></span><a class="phone" href="tel:<?= e(str_replace(' ','',$l['phone'])) ?>"><?= e($l['phone']) ?></a></div><div class="posted">Posted <?= e(time_ago($l['created_at'])) ?> · <?= (int)$l['views'] ?> views</div></div><?php endforeach; endif; ?></div></section>
<?php require 'includes/footer.php'; ?>
