<?php
require 'config.php'; require 'includes/functions.php';
if(current_user()){ header('Location:index.php'); exit; }
$pageTitle='Create account'; $activePage=''; $errors=[];
$roles=$pdo->query("SELECT id,name,description FROM user_roles WHERE name IN ('farmer','trader','buyer') ORDER BY id")->fetchAll();
$regions=$pdo->query('SELECT id,name FROM regions ORDER BY name')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verify_csrf($_POST['csrf_token']??'')) $errors[]='Your session expired. Please try again.';
 $name=trim($_POST['name']??''); $phone=trim($_POST['phone']??''); $email=trim($_POST['email']??''); $role_id=(int)($_POST['role_id']??0); $region_id=(int)($_POST['region_id']??0); $district_id=!empty($_POST['district_id'])?(int)$_POST['district_id']:null; $village=trim($_POST['village']??''); $password=$_POST['password']??''; $confirm=$_POST['confirm']??'';
 if($name==='')$errors[]='Enter your name.'; if(!preg_match('/^[0-9+ ()-]{7,30}$/',$phone))$errors[]='Enter a valid phone number.'; if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))$errors[]='Enter a valid email address.'; if($role_id<=0)$errors[]='Choose an account type.'; if($region_id<=0)$errors[]='Choose your region.'; if(strlen($password)<6)$errors[]='Password must be at least 6 characters.'; if($password!==$confirm)$errors[]="Passwords don't match.";
 if(!$errors){$s=$pdo->prepare('SELECT id FROM users WHERE phone=?');$s->execute([$phone]);if($s->fetch())$errors[]='An account with this phone number already exists.'; if($email!==''){$s=$pdo->prepare('SELECT id FROM users WHERE email=?');$s->execute([$email]);if($s->fetch())$errors[]='An account with this email already exists.';}}
 if(!$errors){$s=$pdo->prepare('SELECT id FROM user_roles WHERE id=? AND name IN (\'farmer\',\'trader\',\'buyer\')');$s->execute([$role_id]);if(!$s->fetch())$errors[]='Invalid account type.';}
 if(!$errors){$s=$pdo->prepare('SELECT id FROM regions WHERE id=?');$s->execute([$region_id]);if(!$s->fetch())$errors[]='Invalid region.';}
 if(!$errors&&$district_id!==null){$s=$pdo->prepare('SELECT id FROM districts WHERE id=? AND region_id=?');$s->execute([$district_id,$region_id]);if(!$s->fetch())$errors[]='Invalid district.';}
 if(!$errors){$s=$pdo->prepare('INSERT INTO users(role_id,name,phone,email,password_hash,region_id,district_id,village) VALUES(?,?,?,?,?,?,?,?)');$s->execute([$role_id,$name,$phone,$email?:null,password_hash($password,PASSWORD_DEFAULT),$region_id,$district_id,$village?:null]);$_SESSION['user_id']=$pdo->lastInsertId();$_SESSION['user_name']=$name;$_SESSION['user_phone']=$phone;header('Location:index.php');exit;}
}
$selected_region=(int)($_POST['region_id']??0); $districts=[]; if($selected_region){$s=$pdo->prepare('SELECT id,name FROM districts WHERE region_id=? ORDER BY name');$s->execute([$selected_region]);$districts=$s->fetchAll();}
require 'includes/header.php'; ?>
<section class="auth-shell"><p class="eyebrow">JOIN SOKONI</p><h1>Create your account</h1><p class="sub-small">Choose how you participate in Tanzania's agricultural market.</p><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><div class="field"><label>Full name</label><input name="name" value="<?= e($_POST['name']??'') ?>" required></div><div class="field"><label>Phone number</label><input name="phone" placeholder="0712 345 678" value="<?= e($_POST['phone']??'') ?>" required></div><div class="field"><label>Email <small>(optional)</small></label><input type="email" name="email" value="<?= e($_POST['email']??'') ?>"></div><div class="field"><label>Account type</label><select name="role_id" required><option value="">Choose type</option><?php foreach($roles as $r): ?><option value="<?= (int)$r['id'] ?>" <?= ((int)($_POST['role_id']??0)===(int)$r['id'])?'selected':'' ?>><?= e(ucfirst($r['name'])) ?></option><?php endforeach; ?></select></div><div class="field"><label>Region</label><select name="region_id" required><option value="">Choose region</option><?php foreach($regions as $r): ?><option value="<?= (int)$r['id'] ?>" <?= $selected_region===(int)$r['id']?'selected':'' ?>><?= e($r['name']) ?></option><?php endforeach; ?></select></div><div class="field"><label>District <small>(optional)</small></label><select name="district_id"><option value="">Choose district</option><?php foreach($districts as $d): ?><option value="<?= (int)$d['id'] ?>" <?= ((int)($_POST['district_id']??0)===(int)$d['id'])?'selected':'' ?>><?= e($d['name']) ?></option><?php endforeach; ?></select></div><div class="field"><label>Village <small>(optional)</small></label><input name="village" value="<?= e($_POST['village']??'') ?>"></div><div class="row2"><div class="field"><label>Password</label><input type="password" name="password" minlength="6" required></div><div class="field"><label>Confirm password</label><input type="password" name="confirm" minlength="6" required></div></div><?php foreach($errors as $err): ?><div class="error"><?= e($err) ?></div><?php endforeach; ?><button class="btn full" type="submit">Create account</button></form><p class="foot">Already have an account? <a href="login.php">Log in</a></p></section>
<?php require 'includes/footer.php'; ?>
